services:
  back:
    build: ./
    volumes:
      - ./back:/back
    ports:
      - 8002:8000
  db:
    image: mysql:8.3
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: practice
      MYSQL_USER: fukushina
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

volumes:
  db: